###########################################################
### Welcome to Beautiful Jekyll!
###########################################################

############################
# --- Required options --- #
############################

title: 秋刀鱼梦
author: 秋刀鱼梦
url: https://xdx95.github.io

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  关于我: "about"
  我的博客: "/"
  我的GitHub: "https://github.com/xdx95"

################
# --- Logo --- #
################

avatar: "/assets/img/avatar.png"
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  rss: true
  github: xdx95
rss-description: 秋刀鱼梦的技术博客

###########################
# --- General options --- #
###########################

share-links-active:
  twitter: false
  facebook: false
  linkedin: false

url-pretty: "xdx95.github.io"
title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true
keywords: "秋刀鱼梦, 技术博客"

######################################
# --- Colours / background image --- #
######################################

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

#################################
# --- Web Analytics Section --- #
#################################

# gtag: "G-XXXXXXXXXX" # 新手先注释，后续配置

####################
# --- Comments --- #
####################

utterances:
  repository: "xdx95/xdx95.github.io"
  issue-term: title
  theme: github-light
  label: blog-comments

################
# --- Misc --- #
################

date_format: "%B %-d, %Y"
timezone: "Asia/Shanghai"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
